version: "3.8"

services:
  disease-predictor-app:
    image: jayant1054/disease-predictor:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      - FLASK_ENV=production
    networks:
      - overlay-network

networks:
  overlay-network:
    driver: overlay
    attachable: true